### PR TITLE
Remove unused Background Task Identifier

### PR DESCRIPTION
**Pull request by skatpgusskat**

### CODE REVIEW

**Comment by skatpgusskat** [comment]
@ocetnik
This code make crash. On `expirationHandler`, task become invalid or something, so when `endBackgroundTask` is executed, app just crash.

Please hot-fix this commit as soon as possible.

**Comment by saghul** [comment]
(Not the author) I haven't seen that behavior, but your patch will prevent the app from running for a bit in the background. Can you give #38 a try? It seems to solve some obscure crashes we've experienced.

**Comment by skatpgusskat** [comment]
@saghul I've never seen that crash. What about trying to change your local source code(`./node_module/react-native-background-timer/......`) like my commit and testing crash?

**Comment by saghul** [comment]
Of course you patch would fix it, because it avoids queuing the task in the background altogether :-) 

The goal of this module is to run background tasks on a timer, as per Apple's rules. Looks like my fix made it to master, I hope it fixes you issue too!

**Pull request closed without merging**
