### PR TITLE
Added iOS support

### PR DESCRIPTION
**Pull request by IjzerenHein**
This pull-request adds support for iOS.

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Hi, I've also added setInterval and clearInterval so it's possible to have multiple background timers.
I'd love to see this in the official release as well.

Cheers, Hein

**Comment by ocetnik** [comment]
Hi Hein,

huge thanks for your great work.

Only one question. Do we need copyright in your files?

Thanks,
Dávid

**Comment by IjzerenHein** [comment]
No we don't, license of this repo will suffice

**Comment by IjzerenHein** [comment]
And, you're welcome. Awesome you pulled this in so quickly :)

**Comment by ocetnik** [comment]
So can I remove licenses from files annotations?

**Comment by IjzerenHein** [comment]
Well please keep a reference that I created the file and ATO gear. You can remove the 'copyright' keyword if necessary, or replace it with a reference to the LICENSE file or that it's MIT.

**Comment by ocetnik** [comment]
And of course I will be very happy if you complete `clearTimeout` method

**Comment by ocetnik** [comment]
I understand you, it's alright.

**Pull request merged**
